spring.application.name=oss-service

server.port=8205

# JSON global time format
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8

# Nacos service address
spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848

spring.data.mongodb.uri=mongodb://root:root@localhost:27017/hospital?authSource=admin

#change to own aliyun oss key
aliyun.oss.accessKeyId=LT6I0Y5633pX89qC
aliyun.oss.secret=jX8D04Dm12I3gGKj345FYSzu0fq8mT
aliyun.oss.endpoint=http://oss-cn-shenzhen.aliyuncs.com
aliyun.oss.bucket=