spring.application.name=gateway-service
# server port
server.port=89

# nacos service address
spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848

#Use service discovery for routing
spring.cloud.gateway.discovery.locator.enabled=true

#hospital
spring.cloud.gateway.routes[0].id=hospital-service
spring.cloud.gateway.routes[0].uri=lb://hospital-service
#Set route predicates, proxy /auth/ path for serviceId auth-service
spring.cloud.gateway.routes[0].predicates= Path=/*/hospital/**

#dictionary
spring.cloud.gateway.routes[1].id=data-service
spring.cloud.gateway.routes[1].uri=lb://data-service
spring.cloud.gateway.routes[1].predicates= Path=/*/dataManagement/**

#user
spring.cloud.gateway.routes[2].id=user-service
spring.cloud.gateway.routes[2].uri=lb://user-service
spring.cloud.gateway.routes[2].predicates= Path=/*/user/**

#sms
spring.cloud.gateway.routes[3].id=sms-service
spring.cloud.gateway.routes[3].uri=lb://sms-service
spring.cloud.gateway.routes[3].predicates= Path=/*/sms/**

#weixin
spring.cloud.gateway.routes[4].id=user-service
spring.cloud.gateway.routes[4].uri=lb://user-service
spring.cloud.gateway.routes[4].predicates= Path=/*/weixin/**

#oss
spring.cloud.gateway.routes[5].id=oss-service
spring.cloud.gateway.routes[5].uri=lb://oss-service
spring.cloud.gateway.routes[5].predicates= Path=/*/oss/**